/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.diegoalba.rentalcar.views;

import es.diegoalba.rentalcar.model.GestorVehiculos;
import es.diegoalba.rentalcar.model.Vehiculo;
import es.diegoalba.rentalcar.persistence.LectorObjetos;
import java.util.LinkedList;

/**
 *
 * @author USUARIO
 */
public class JDialogEliminarVehiculo extends javax.swing.JDialog {

    private VehiculosTableModel modeloVehiculos;
    private LinkedList<Vehiculo> listaVehiculos;
    
    /**
     * Creates new form JDialogEliminarVehiculo
     */
    public JDialogEliminarVehiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
                        
        this.numero = -1;
        LectorObjetos lectorVehiculos = new LectorObjetos("vehiculos.dam");
        listaVehiculos = lectorVehiculos.read();
        
        modeloVehiculos = new VehiculosTableModel(listaVehiculos);
        
        
        
        
        
        
        initComponents();
        setLocationRelativeTo(parent);

    }

    public int getNumero() {
        return numero;
    }

    public int getEstadoFinal() {
        return estadoFinal;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonEliminarVe = new javax.swing.JButton();
        jButtonCancelarElimVe = new javax.swing.JButton();
        jTextFieldNumAElim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Eliminar Vehiculo");

        jButtonEliminarVe.setForeground(new java.awt.Color(255, 0, 0));
        jButtonEliminarVe.setText("Eliminar");
        jButtonEliminarVe.setEnabled(false);
        jButtonEliminarVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarVeActionPerformed(evt);
            }
        });

        jButtonCancelarElimVe.setText("Cancelar");
        jButtonCancelarElimVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarElimVeActionPerformed(evt);
            }
        });

        jTextFieldNumAElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumAElimActionPerformed(evt);
            }
        });
        jTextFieldNumAElim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumAElimKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Numero:");

        jTable1.setModel(modeloVehiculos);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButtonEliminarVe)
                        .addGap(49, 49, 49)
                        .addComponent(jButtonCancelarElimVe))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumAElim, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNumAElim, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEliminarVe)
                            .addComponent(jButtonCancelarElimVe)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNumAElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumAElimActionPerformed
        // TODO add your handling code here:

         
    }//GEN-LAST:event_jTextFieldNumAElimActionPerformed

    private void jButtonCancelarElimVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarElimVeActionPerformed
        // TODO add your handling code here:
        doClose(0);
    }//GEN-LAST:event_jButtonCancelarElimVeActionPerformed

    private void jButtonEliminarVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarVeActionPerformed
        // TODO add your handling code here:
        String num = jTextFieldNumAElim.getText();
        this.numero = Integer.parseInt(num);
        this.numero = numero-1;
        //TRAZA
        System.out.printf("Tecleado: %s %n",num);
        
        GestorVehiculos gestor = new GestorVehiculos("vehiculos.dam","vehiculos.dam");
        
        gestor.cargarVehiculos();
        gestor.eliminarVehiculo(numero);
        gestor.guardarVehiculos();
        doClose(1);
    }//GEN-LAST:event_jButtonEliminarVeActionPerformed

    private void jTextFieldNumAElimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumAElimKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        String texto2;
        
        //TRAZA
        System.out.printf("He tecleado %c en Num2 %n",car);
        
        if(!Character.isDigit(car)){ //Si no es digito, ignoralo
            evt.consume(); //Ignora el evento
            texto2 = jTextFieldNumAElim.getText();
        } else {
            texto2 = jTextFieldNumAElim.getText() + car;
        }        
        
        
        if(!texto2.isEmpty() ){
            jButtonEliminarVe.setEnabled(true);
        } else {
            jButtonEliminarVe.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldNumAElimKeyTyped

    private void doClose(int estado){
        // Ocultar el dialogo
        estadoFinal = estado;
        setVisible(false);
        dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogEliminarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogEliminarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogEliminarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogEliminarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogEliminarVehiculo dialog = new JDialogEliminarVehiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarElimVe;
    private javax.swing.JButton jButtonEliminarVe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldNumAElim;
    // End of variables declaration//GEN-END:variables
    
    private int numero;
    private int estadoFinal;
}
