/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.diegoalba.rentalcar.views;

import es.diegoalba.rentalcar.model.GestorVehiculos;
import es.diegoalba.rentalcar.model.Vehiculo;
import es.diegoalba.rentalcar.persistence.LectorObjetos;
import java.util.LinkedList;

/**
 *
 * @author b09-05m
 */
public class JDialogListaVehiculos extends javax.swing.JDialog {

    private VehiculosTableModel modeloVehiculos;
    private LinkedList<Vehiculo> listaVehiculos;
    
    /**
     * Creates new form JDialogListaVehiculos
     */
    public JDialogListaVehiculos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
//                
//        Cliente c1 = new Cliente("Juan Perez",65.78,true,"Sin comentario");
//        Cliente c2 = new Cliente("Marcos Perez",70.78,false,"Baja en Junio");
//        
//        LinkedList<Cliente> lista = new LinkedList<>();
//        lista.add(c1);
//        lista.add(c2);
//        
//        modeloClientes = new ClientesTableModel(lista);
//        //Dentro se crea el JTable usando como model el nodeloClientes.
        LectorObjetos lectorVehiculos = new LectorObjetos("vehiculos.dam");
        listaVehiculos = lectorVehiculos.read();
        
        modeloVehiculos = new VehiculosTableModel(listaVehiculos);
        
        initComponents();
        setLocationRelativeTo(parent);
    }

    public Vehiculo getVe() {
        return ve;
    }

    public int getNumeroV() {
        return numeroV;
    }

    public int getEstadoFinal() {
        return estadoFinal;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonListaAlquilar = new javax.swing.JButton();
        jButtonListaDevolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldListaEditarVehiculo = new javax.swing.JTextField();
        jToggleButtonListaSalir = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(modeloVehiculos);
        jScrollPane1.setViewportView(jTable1);

        jButtonListaAlquilar.setText("Alquilar");
        jButtonListaAlquilar.setEnabled(false);
        jButtonListaAlquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaAlquilarActionPerformed(evt);
            }
        });

        jButtonListaDevolver.setText("Devolver");
        jButtonListaDevolver.setEnabled(false);
        jButtonListaDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaDevolverActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero Vehiculo:");

        jTextFieldListaEditarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldListaEditarVehiculoActionPerformed(evt);
            }
        });

        jToggleButtonListaSalir.setText("Salir");
        jToggleButtonListaSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonListaSalirActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Pulsar Intro despues de añadirel numero ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(128, 128, 128))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButtonListaAlquilar)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonListaDevolver)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldListaEditarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButtonListaSalir)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldListaEditarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListaAlquilar)
                    .addComponent(jButtonListaDevolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonListaSalir)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonListaSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonListaSalirActionPerformed
        // TODO add your handling code here:
        doClose(-1);
    }//GEN-LAST:event_jToggleButtonListaSalirActionPerformed

    private void jTextFieldListaEditarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldListaEditarVehiculoActionPerformed
        // TODO add your handling code here:
        ve = null;
        numVehiculo = jTextFieldListaEditarVehiculo.getText();
        numeroV = Integer.parseInt(numVehiculo);
        numeroV = numeroV - 1;
        ve = listaVehiculos.get(numeroV);
        
        //TRAZA
        System.out.println(ve);
        
        if(ve.isDisponible()){
            jButtonListaAlquilar.setEnabled(true);
        } else {
            jButtonListaDevolver.setEnabled(true);
        }
        
    }//GEN-LAST:event_jTextFieldListaEditarVehiculoActionPerformed

        private void doClose(int estado){
        // Ocultar el dialogo
        estadoFinal = estado;
        setVisible(false);
        dispose();
    }
    
    private void jButtonListaDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaDevolverActionPerformed
        // TODO add your handling code here:
                GestorVehiculos gestor = new GestorVehiculos("vehiculos.dam","vehiculos.dam");
        ve.setDisponible(true);
        
        //TRAZA
        System.out.println(ve);
        
        doClose(0);
    }//GEN-LAST:event_jButtonListaDevolverActionPerformed

    private void jButtonListaAlquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaAlquilarActionPerformed
        // TODO add your handling code here:
        GestorVehiculos gestor = new GestorVehiculos("vehiculos.dam","vehiculos.dam");
        ve.setDisponible(false);
        
        //TRAZA
        System.out.println(ve);
        
        doClose(1);
    }//GEN-LAST:event_jButtonListaAlquilarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogListaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogListaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogListaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogListaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogListaVehiculos dialog = new JDialogListaVehiculos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonListaAlquilar;
    private javax.swing.JButton jButtonListaDevolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldListaEditarVehiculo;
    private javax.swing.JToggleButton jToggleButtonListaSalir;
    // End of variables declaration//GEN-END:variables
    private VehiculosTableModel modeloTablaVehiculos;

    
    private String numVehiculo;
    private int numeroV;
    private Vehiculo ve;
    private int estadoFinal;

}
