/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.diegoalba.rentalcar.views;

import es.diegoalba.rentalcar.model.GestorVehiculos;
import es.diegoalba.rentalcar.model.Vehiculo;
import es.diegoalba.rentalcar.persistence.EscritorObjetos;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author b09-05m
 */
public class JDialogAñadirVehiculo extends javax.swing.JDialog {

    /**
     * Creates new form JDialogAñadirVehiculo
     */
    public JDialogAñadirVehiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        
        jTextFieldEstado.setText("DISPONIBLE");
        this.matricula = null;
        this.marca = null;
        this.modelo = null;
        this.pulsoAceptar = false;
        this.estado = true;

        
    }

    public boolean isPulsoAceptar() {
        return pulsoAceptar;
    }

    public String getMatricula() {
        return matricula;
    }

    public String getModelo() {
        return modelo;
    }
    
    public String getMarca() {
        return marca;
    }

    public int getEstadoFinal() {
        return estadoFinal;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMatricula = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldEstado = new javax.swing.JTextField();
        jLabelFotoCoche = new javax.swing.JLabel();
        jButtonAñadirVOk = new javax.swing.JButton();
        jButtonAñadirVCancel = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelMatricula.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelMatricula.setText("Matricula:");
        jLabelMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelMarca.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelMarca.setText("Marca:");

        jLabelModelo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelModelo.setText("Modelo:");

        jLabelEstado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelEstado.setText("Estado:");

        jTextFieldMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatriculaActionPerformed(evt);
            }
        });
        jTextFieldMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatriculaKeyTyped(evt);
            }
        });

        jTextFieldMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMarcaActionPerformed(evt);
            }
        });
        jTextFieldMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMarcaKeyTyped(evt);
            }
        });

        jTextFieldModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModeloActionPerformed(evt);
            }
        });
        jTextFieldModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldModeloKeyTyped(evt);
            }
        });

        jTextFieldEstado.setEditable(false);
        jTextFieldEstado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldEstado.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstadoActionPerformed(evt);
            }
        });

        jButtonAñadirVOk.setText("Ok");
        jButtonAñadirVOk.setEnabled(false);
        jButtonAñadirVOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirVOkActionPerformed(evt);
            }
        });

        jButtonAñadirVCancel.setText("Cancel");
        jButtonAñadirVCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirVCancelActionPerformed(evt);
            }
        });

        jButton3.setText("Seleccionar Imagen...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMarca)
                            .addComponent(jLabelModelo)
                            .addComponent(jLabelEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldMatricula)
                                .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabelFotoCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonAñadirVOk)
                                .addGap(62, 62, 62)
                                .addComponent(jButtonAñadirVCancel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(14, 14, 14)))
                        .addGap(149, 149, 149))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMarca)
                            .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelModelo)
                            .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEstado))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelFotoCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAñadirVOk)
                    .addComponent(jButtonAñadirVCancel))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModeloActionPerformed

    private void jButtonAñadirVOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirVOkActionPerformed
        // TODO add your handling code here:

        this.matricula = jTextFieldMatricula.getText();
        this.modelo = jTextFieldModelo.getText();
        this.marca = jTextFieldMarca.getText();
        this.pulsoAceptar = true;
        
        //TRAZA
        System.out.printf("Tecleado: %s-%s-%s  %n",matricula,modelo,marca);
        
        Vehiculo VehiculoNuevo = new Vehiculo(matricula,marca,modelo);
        EscritorObjetos escritorV = new EscritorObjetos("vehiculos.dam");
        GestorVehiculos gestor = new GestorVehiculos();
        
        escritorV.añadir(VehiculoNuevo);
        gestor.guardarVehiculos();
        
        jTextFieldMatricula.setText("");
        jTextFieldMarca.setText("");
        jTextFieldModelo.setText("");
        jLabelFotoCoche.setIcon(null);
        
        doClose(1);
    }//GEN-LAST:event_jButtonAñadirVOkActionPerformed
    
    private void closeDialog(WindowEvent evt){
        doClose(0);
    }
    
    private void doClose(int estado){
        // Ocultar el dialogo
        estadoFinal = estado;
        setVisible(false);
        dispose();
    }
    
    private void jButtonAñadirVCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirVCancelActionPerformed
        // TODO add your handling code here:
        this.pulsoAceptar = false;
        jTextFieldMatricula.setText("");
        jTextFieldMarca.setText("");
        jTextFieldModelo.setText("");
        jLabelFotoCoche.setIcon(null);
        doClose(0);
        
        
    }//GEN-LAST:event_jButtonAñadirVCancelActionPerformed

    private String abreDialogo(){
        JFileChooser dlgFileChooser = new JFileChooser();
        
        // ...solo para ficheros JFileChhoser.FILES_ONLY
        // ...solo para ficheros JFileChhoser.DIRECTORIES_ONLY
        // ...solo para ficheros JFileChhoser.FILES_AND_DIRECTORIES
        dlgFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        //...solo imagenes
        FileNameExtensionFilter filtroImagen = 
                    new FileNameExtensionFilter("Archivos de imagen","jpg","png","jpeg"); 
        
        //....solo musica
        FileNameExtensionFilter filtroMusica = 
                    new FileNameExtensionFilter("Archivos de audio","mp4","mp3");
        
        dlgFileChooser.addChoosableFileFilter(filtroImagen);
        //dlgFileChooser.addChoosableFileFilter(filtroMusica);
        
        //...eliminar "todos los archivos"
        dlgFileChooser.setAcceptAllFileFilterUsed(true);
        
        //....NO mostrar ficheros ocultos
        dlgFileChooser.setFileHidingEnabled(false);
        
        dlgFileChooser.setCurrentDirectory(new File("D:/"));
        
        //Muestro el dialogo
        int ret = dlgFileChooser.showOpenDialog(this);
        
        //El dialogo se cerro, ¿que sucedio?
        if(ret != JFileChooser.APPROVE_OPTION){
            //NO ha hecho click en OK/yes
            return null;
        }
        
        //Hizo click en Aceptar/ok/yes
        File fichero = dlgFileChooser.getSelectedFile();
        
        //Devuelvo el nombre con la ruta absoluta
        return fichero.getAbsolutePath();
    }
    
    /**
     * Metodo que escala la imagen a la etiqueta.
     * @param ruta La imagen.
     * @param label LA etiqueta a la que se adaptara.
     */
    public void escalarImg(String ruta, JLabel label){
        ImageIcon img = new ImageIcon(ruta);
        Icon icono = new ImageIcon(
                   img.getImage().getScaledInstance(
                           jLabelFotoCoche.getWidth(),jLabelFotoCoche.getHeight(),1));
        
        label.setIcon(icono);
        this.repaint();
    }
        
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         
        //Muestro el dialogo con JChooser
        String rutaImg = abreDialogo();
        escalarImg(rutaImg,jLabelFotoCoche);
        
        /* El dialogo se ha cerrado: COMPROBAR QUE PASO
        * Aceptó ---> File tiene nombre/ruta de fichero.
        * Rechazo ---> File es null
        */ 
//        if(filename==null){
////            txtFichero.setText("No has seleccionado nada!");
//            
//        }else {
////            txtFichero.setText(filename);
//            
//            //Ademas cargo la imagen y la muestro
//            jLabelFotoCoche.setIcon(new ImageIcon(filename));
//        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstadoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldEstadoActionPerformed

    private void jTextFieldMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatriculaActionPerformed

    private void jTextFieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMarcaActionPerformed

    private void jTextFieldMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        String texto2;
        
        //TRAZA
        System.out.printf("He tecleado %c en Num2 %n",car);
        
        if(!Character.isLetter(car) && !Character.isDigit(car)){ //Si no es digito, ignoralo
            evt.consume(); //Ignora el evento
            texto2 = jTextFieldMatricula.getText();
        } else {
            texto2 = jTextFieldMatricula.getText() + car;
        }        
        
        
        if(!texto2.isEmpty() && !jTextFieldMarca.getText().isEmpty() && !jTextFieldModelo.getText().isEmpty()){
            jButtonAñadirVOk.setEnabled(true);
        } else {
            jButtonAñadirVOk.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldMatriculaKeyTyped

    private void jTextFieldMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMarcaKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        String texto2;
        
        //TRAZA
        System.out.printf("He tecleado %c en Num2 %n",car);
        
        if(!Character.isLetter(car) && !Character.isDigit(car)){ //Si no es digito, ignoralo
            evt.consume(); //Ignora el evento
            texto2 = jTextFieldMarca.getText();
        } else {
            texto2 = jTextFieldMarca.getText() + car;
        }        
        
        
        if(!texto2.isEmpty() && !jTextFieldMatricula.getText().isEmpty() && !jTextFieldModelo.getText().isEmpty()){
            jButtonAñadirVOk.setEnabled(true);
        } else {
            jButtonAñadirVOk.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldMarcaKeyTyped

    private void jTextFieldModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldModeloKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        String texto2;
        
        //TRAZA
        System.out.printf("He tecleado %c en Num2 %n",car);
        
        if(!Character.isLetter(car) && !Character.isDigit(car)){ //Si no es digito, ignoralo
            evt.consume(); //Ignora el evento
            texto2 = jTextFieldModelo.getText();
        } else {
            texto2 = jTextFieldModelo.getText() + car;
        }        
        
        
        if(!jTextFieldMarca.getText().isEmpty() && !jTextFieldMatricula.getText().isEmpty() && !texto2.isEmpty()){
            jButtonAñadirVOk.setEnabled(true);
        } else {
            jButtonAñadirVOk.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldModeloKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogAñadirVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogAñadirVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogAñadirVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAñadirVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogAñadirVehiculo dialog = new JDialogAñadirVehiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAñadirVCancel;
    private javax.swing.JButton jButtonAñadirVOk;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFotoCoche;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldModelo;
    // End of variables declaration//GEN-END:variables
    
      //Mis atributos
    private boolean pulsoAceptar;
    private boolean estado;
    private String matricula;
    private String modelo;
    private String marca;
    private String rutaImg;
    
    private int estadoFinal = 0;

}
